#!/bin/bash

# Sauvegarde des données
# Projet Usagi OS

# Informations
# en = Ethernet,
# wl = Wireless LAN (WLAN),
# ww for wireless wide area network (WWAN)


MACOUTPUT=`cat /sys/class/net/en*/address`
if [[ "${MACOUTPUT,,}" == "" ]];
then
	MACOUTPUT=`cat /sys/class/net/wl*/address`
	if [[ "${MACOUTPUT,,}" == "" ]];
	then
		MACOUTPUT=`cat /sys/class/net/ww*/address`
	fi
fi

cp -dR /etc/usagi/$MACOUTPUT/* /

modprobe zram
RAMSIZE=`free -g | awk '/Mem\:/ { print $2 }'`
chmod 777 /sys/block/zram0/disksize
echo $(((RAMSIZE*1000000000))) > /sys/block/zram0/disksize
mkswap -L zramswap /dev/zram0
swapon -p 100 /dev/zram0