#!/bin/bash

# Sauvegarde des données
# Projet Usagi OS

# Informations
# en = Ethernet,
# wl = Wireless LAN (WLAN),
# ww for wireless wide area network (WWAN)


MACOUTPUT=`cat /sys/class/net/en*/address`
if [[ "${MACOUTPUT,,}" == "" ]];
then
	MACOUTPUT=`cat /sys/class/net/wl*/address`
	if [[ "${MACOUTPUT,,}" == "" ]];
	then
		MACOUTPUT=`cat /sys/class/net/ww*/address`
	fi
fi

mkdir -p /etc/usagi/$MACOUTPUT

mkdir -p /etc/usagi/$MACOUTPUT/usr /etc/usagi/$MACOUTPUT/usr/share /etc/usagi/$MACOUTPUT/usr/share/X11 /etc/usagi/$MACOUTPUT/usr/share/X11/xorg.conf.d
cp -dR /usr/share/X11/xorg.conf.d/* /etc/usagi/$MACOUTPUT/usr/share/X11/xorg.conf.d/

mkdir -p /etc/usagi/$MACOUTPUT/etc /etc/usagi/$MACOUTPUT/etc/X11 /etc/usagi/$MACOUTPUT/etc/X11/xorg.conf.d
cp -dR /etc/X11/xorg.conf.d/* /etc/usagi/$MACOUTPUT/etc/X11/xorg.conf.d/
cp -dR /etc/fstab /etc/usagi/$MACOUTPUT/etc/fstab

getent passwd | while IFS=: read -r name password uid gid gecos home shell; do
  if [[ $home == *"/home"* ]]; then
	  mkdir -p /etc/usagi/$MACOUTPUT/home/ /etc/usagi/$MACOUTPUT/home/$name /etc/usagi/$MACOUTPUT/home/$name/.config /etc/usagi/$MACOUTPUT/home/$name/.config/autostart
	  mv /home/$name/.config/autostart/lxrandr-autostart.desktop /etc/usagi/$MACOUTPUT/home/$name/.config/autostart/
  fi
done

chmod 777 -R /etc/usagi/$MACOUTPUT
